### ISSUE TITLE
How can I mock hard dependencies with Mockery and Codeception?

### ISSUE THREAD

**Issue by 501st-alpha1** [Codeception/MockeryModule#8]
According to [the Mockery docs](http://docs.mockery.io/en/latest/cookbook/mocking_hard_dependencies.html), I can mock hard dependencies by doing e.g.:

```php
$mock = m::mock('overload:SomeNamespace\SomeClass');
```

However, this only works if the mocked class is not loaded somewhere else in the test suite.

Quoting from the docs:
> To make this possible, we’ll tell PHPUnit to run the tests that have overloaded classes in separate processes and to not preserve global state. That way we’ll avoid having the overloaded class included more than once. Of course this has its downsides as these tests will run slower.

This means adding the `@runTestsInSeparateProcesses` and `@preserveGlobalState disabled` annotations. When I did so, I got this error:

```
PHPUnit_Framework_Exception: PHP Fatal error:  Class 'Codeception\TestCase\Test' not found in [snip]
Fatal error: Class 'Codeception\TestCase\Test' not found in [snip]
```

After some searching, I found [this GitHub issue](https://github.com/Codeception/Codeception/issues/1556#issuecomment-67593284), which says that Codeception doesn't support the `@runTestsInSeparateProcesses` annotation.

Is there any way around this, or some other way to mock hard dependencies?

**Comment by enumag** [comment]
None that I'm aware of. I almost never use hard dependencies so I never needed this.

**Comment by 501st-alpha1** [comment]
Okay, thanks. I've switched to [AspectMock](https://github.com/Codeception/AspectMock) for now, which supports hard dependecies.
